Bump to v0.7.5-alpha fix files test

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -177,25 +177,32 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create-release.outputs.upload_url }}
-          asset_path: robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
+          asset_path: ./robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
           asset_name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
           asset_content_type: application/zip
 
-      - name: 'Download linux Build Artifact'
+      - name: 'Download macOS Build Artifact'
         uses: actions/download-artifact@v4
         with:
           path: .
-          name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-linux-x64.zip
+          name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
 
-      - name: 'Upload linux Build Artifact'
-        id: upload-release-linux-zip-asset
+      - name: 'Verify macOS Build Artifact'
+        run: |
+          if [ ! -f "robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip" ]; then
+            echo "Error: macOS build artifact not found!"
+            exit 1
+          fi
+
+      - name: 'Upload macOS Build Artifact'
+        id: upload-release-mac-zip-asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create-release.outputs.upload_url }}
-          asset_path: robosats-desktop-${{ needs.check-versions.outputs.semver }}-linux-x64.zip
-          asset_name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-linux-x64.zip
+          asset_path: robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
+          asset_name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-mac-darwin-x64.zip
           asset_content_type: application/zip
 
       - name: 'Download Windows Build Artifact'
@@ -211,6 +218,6 @@ jobs:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         with:
           upload_url: ${{ steps.create-release.outputs.upload_url }}
-          asset_path: robosats-desktop-${{ needs.check-versions.outputs.semver }}-win32-ia32.zip
+          asset_path: ./robosats-desktop-${{ needs.check-versions.outputs.semver }}-win32-ia32.zip
           asset_name: robosats-desktop-${{ needs.check-versions.outputs.semver }}-win32-ia32.zip
           asset_content_type: application/zip
